language: bash
sudo: false
os:
- linux
# - osx
env:
  global:
  - GIMME_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - GO_VERSIONS="$(< .known-binary-versions-$UNAME) $(< .known-source-versions-$UNAME)"
  - GO_ARM_VERSIONS="$(< .known-source-versions-$UNAME)"
before_script: mkdir -p "${GIMME_TMP}"
script:
- ./gimme -h
- ./gimme -V
- for v in $GO_VERSIONS ; do
    echo "---> eval \"\$(./gimme $v)\"" ;
    eval "$(./gimme $v)" ;
  done ;
- if [[ $UNAME = linux ]] ; then
    for v in $GO_ARM_VERSIONS ; do
      echo "---> eval \"\$(GIMME_ARCH=arm ./gimme $v)\"" ;
      eval "$(GIMME_ARCH=arm ./gimme $v)" ;
    done ;
  fi ;
- ./gimme -l
