language: bash
env:
  matrix:
  - GIMME_GO_VERSION=1.4
  - GIMME_GO_VERSION=1.3.3
  - GIMME_GO_VERSION=1.1
  - GIMME_GO_VERSION=1.0.3
  - GIMME_GO_VERSION=go1
  global:
  - GIMME_TMP="/var/tmp/gimme"
script:
- ./gimme
- source ~/.gimme/envs/$GIMME_GO_VERSION
- go version
