language: bash
sudo: false
os:
- osx
- linux
env:
  global:
  - GIMME_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - GO_VERSIONS="$(< .known-binary-versions-$UNAME) $(< .known-source-versions-$UNAME)"
before_script: mkdir -p "${GIMME_TMP}"
script: for v in $GO_VERSIONS ; do
    echo "---> ./gimme $v" ;
    ./gimme $v ;
  done ;
  if [[ $UNAME = linux ]] ; then
    echo "---> GIMME_ARCH=arm ./gimme $v" ;
    GIMME_ARCH=arm ./gimme $v ;
  fi
