language: bash
sudo: false
env:
  matrix:
  - GIMME_GO_VERSION=1.4
  - GIMME_GO_VERSION=1.3.3
  - GIMME_GO_VERSION=1.3.2
  - GIMME_GO_VERSION=1.3.1
  - GIMME_GO_VERSION=1.3
  - GIMME_GO_VERSION=1.2.2
  - GIMME_GO_VERSION=1.1
  - GIMME_GO_VERSION=1.1.2
  - GIMME_GO_VERSION=1.1.1
  - GIMME_GO_VERSION=1.0.3
  - GIMME_GO_VERSION=1.0.2
  - GIMME_GO_VERSION=1.0.1
  - GIMME_GO_VERSION=go1
  global:
  - GIMME_TMP="/var/tmp/gimme"
  - GIMME_DEBUG=1
script:
- ./gimme
- source ~/.gimme/envs/$GIMME_GO_VERSION
- go version
