sudo: required
dist: trusty
language: bash
os:
- linux
- osx
env:
  global:
  - GIMME_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - GO_VERSIONS="$(< .known-binary-versions-$UNAME) $(< .known-source-versions-$UNAME)"
  - GO_BOOTSTRAP_VERSION=1.4.1
  matrix:
  - TARGET=native
  - TARGET=arm
  - TARGET=arm64
addons:
  apt:
    packages:
    # install cross compilers for cgo support.
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross
before_script:
- mkdir -p "${GIMME_TMP}"
- if [[ "${TARGET}" = "arm" ]] ; then
    export GO_VERSIONS="master" ;
  fi
script:
- ./gimme -h
- ./gimme -V
- ./runtests "${TARGET}" "${GO_BOOTSTRAP_VERSION}" ${GO_VERSIONS}
- ./gimme -l
