language: bash
sudo: false
os:
- osx
- linux
env:
  global:
  - GIMME_TMP="/var/tmp/gimme"
  - GIMME_ENVS_DIR="/var/tmp/gimme/envs"
  - GIMME_VERSIONS_DIR="/var/tmp/gimme/versions"
script: ./test-install $(< known-binary-versions)
