language: bash
sudo: false
os:
- osx
- linux
env:
  global:
  - GIMME_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - GIMME_DEBUG=1
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - GO_VERSIONS="$(< .known-binary-versions-$UNAME) $(< .known-source-versions-$UNAME)"
before_script: mkdir -p "${GIMME_TMP}"
script: for v in $GO_VERSIONS ; do ./gimme $v ; done
